### ISSUE TITLE
Appears not to work with e.g. JSON::Fast

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/OrderedHash#2]
I was looking at this as a possible quick fix for e.g. https://github.com/jonathanstowe/META6/issues/15, hoping (admittedly without any evidence,) that passing an `OrderedHash` to `to-json` (from `JSON::Fast`,) would preserve the order of the keys.

But it appears not to find the keys at all:

```
raku -MOrderedHash -MJSON::Fast -e 'my %oh3 does OrderedHash[:keys<c b a>] = b => 2, c => 1, a => 3; say to-json(%oh3)'
{
}
```

Now this could equally be a problem with `JSON::Fast` but my instinct is that `OrderedHash` isn't quite Hashy enough for `JSON::Fast`.

It would be cool to get this working so I'll try and dig in later.

:+1:

**Comment by jonathanstowe** [comment]
It looks like that `list` needs to be implemented.

**Comment by FCO** [comment]
PR accepted, thank you! I'm on vacation without my computer, I'll need to be at home to release it... :(

**Comment by jonathanstowe** [comment]
Not at all urgent.  Enjoy your holiday! :+1:

**Comment by 2colours** [comment]
@FCO everything fine? It would be nice to close this and get a fixed release. :)

**Comment by FCO** [comment]
I completely forgot about that! Sorry you all! I'll do that later today

**Comment by FCO** [comment]
just released. Sorry for the delay.

**Comment by jonathanstowe** [comment]
Not a problem chief, haven't really had the time to make the changes that would have needed it anyway:  basically it entails adjusting the `JSON::Marshal` such that it can be supplied an explicit order of keys *or* if the object supplied does some role then obtain the order from the object, then rather than using a plain hash use an OrderedHash to construct the data to be serialized to JSON.  Then adjust the `JSON::Class` and all the other things to use this.....
